### ISSUE TITLE
NullPointerException in RAML plugin

### ISSUE THREAD

**Issue by mikaelstaldal** [machaval/mule-intellij-plugins#50] opened 2016-10-12 09:25 UTC
I get this when opening a RAML file:

```
null
java.lang.NullPointerException
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.generateRule(TypeToRuleVisitor.java:89)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitArray(TypeToRuleVisitor.java:323)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitArray(TypeToRuleVisitor.java:66)
    at org.raml.v2.internal.impl.v10.type.ArrayResolvedType.visit(ArrayResolvedType.java:149)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.generateRule(TypeToRuleVisitor.java:89)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitObject(TypeToRuleVisitor.java:158)
    at org.raml.v2.internal.impl.v10.type.TypeToRuleVisitor.visitObject(TypeToRuleVisitor.java:66)
    at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.visit(ObjectResolvedType.java:275)
    at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.validate(ExampleValidationPhase.java:128)
    at org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase.apply(ExampleValidationPhase.java:79)
    at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:95)
    at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:79)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:110)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:98)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:93)
    at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:37)
    at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:18)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:212)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by javaduke** [comment] 2017-03-24 23:12
Can you please attach your RAML file?

**Comment by mikaelstaldal** [comment] 2017-03-27 09:20
No, after almost 6 month I have forgotten which RAML file it was.

**Comment by javaduke** [comment] 2017-04-03 17:54
Sorry, I'm unable to reproduce this issue. I will close this ticket, but if you ever get this error again, please open a ticket and attach the RAML file.

Thank you.

**Closed by javaduke** 2017-04-03 17:54 UTC
