### ISSUE TITLE
StringIndexOutOfBoundsException when using autocompletion (RAML plugin)

### ISSUE THREAD

**Issue by manumouton** [machaval/mule-intellij-plugins#76] opened 2017-03-06 13:32 UTC
Hello, 

Configuration : 
`IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_65-b17 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
`

`String index out of range: 1082
java.lang.StringIndexOutOfBoundsException: String index out of range: 1082
	at java.lang.String.substring(String.java:1963)
	at org.raml.v2.internal.impl.RamlSuggester.stripLastChanges(RamlSuggester.java:250)
	at org.raml.v2.internal.impl.RamlSuggester.getRootNode(RamlSuggester.java:237)
	at org.raml.v2.internal.impl.RamlSuggester.getSuggestionsAt(RamlSuggester.java:176)
	at org.raml.v2.internal.impl.RamlSuggester.getSuggestions(RamlSuggester.java:107)
	at org.raml.v2.internal.impl.RamlSuggester.suggestions(RamlSuggester.java:74)
	at org.mule.tooling.lang.raml.completion.RamlCompletionContributor$RamlCompletionParametersCompletionProvider.addCompletions(RamlCompletionContributor.java:45)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by javaduke** [comment] 2017-03-06 14:41
Is it consistently reproduced? If yes, what are the steps?

**Comment by manumouton** [comment] 2017-03-07 06:26
Hi there, 

this is weird I cannot reproduce it today. This happened several time while I was trying to use autocompletion inside an existing Raml file.

Will keep you updated if I manage to reproduce it once again and will try to be more detailed.

Regards

**Comment by javaduke** [comment] 2017-03-07 14:37
OK, I'll keep this ticket open for now, if and when you are able to reproduce it, please attach the RAML file and describe the steps to reproduce. Based on the stack trace, it seems like the problem is in the older version of the RAML tooling, and the RAML plugin 0.8 uses the newer version, so the issue may be fixed there.

**Comment by javaduke** [comment] 2017-06-21 14:10
RAML Parser updated to 1.0.10 in #89 , I'm going to close this for now, please feel free to reopen if you can reproduce the issue.

**Closed by javaduke** 2017-06-21 14:10 UTC
