### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Number error editing raml file

### ISSUE THREAD

**Issue by glodieu** [machaval/mule-intellij-plugins#77] opened 2017-03-07 20:05 UTC
While editing RAML file Intellij Idea throws this exception.

```
2017-03-07 17:02:53,796 [7789117]  ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 2016.3.5  Build #IU-163.13906.18 
2017-03-07 17:02:53,797 [7789118]  ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_112-release 
2017-03-07 17:02:53,797 [7789118]  ERROR - til.concurrency.QueueProcessor - VM: OpenJDK 64-Bit Server VM 
2017-03-07 17:02:53,797 [7789118]  ERROR - til.concurrency.QueueProcessor - Vendor: JetBrains s.r.o 
2017-03-07 17:02:53,797 [7789118]  ERROR - til.concurrency.QueueProcessor - OS: Mac OS X 
2017-03-07 17:02:53,797 [7789118]  ERROR - til.concurrency.QueueProcessor - Last Action: EditorCopy 
```

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.raml.yagi.framework.util.NodeSelector.selectNumberValue(NodeSelector.java:75)
	at org.raml.v2.internal.impl.v10.type.NumberResolvedType.overwriteFacets(NumberResolvedType.java:102)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.resolveTypeDefinition(TypeDeclarationNode.java:99)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.getResolvedType(TypeDeclarationNode.java:85)
	at org.raml.v2.internal.impl.v10.nodes.PropertyNode.getTypeDefinition(PropertyNode.java:53)
	at org.raml.v2.internal.impl.v10.type.PropertyFacets.getValueType(PropertyFacets.java:59)
	at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.validateFacets(ObjectResolvedType.java:259)
	at org.raml.v2.internal.impl.v10.type.ObjectResolvedType.validateState(ObjectResolvedType.java:242)
	at org.raml.v2.internal.impl.commons.nodes.TypeDeclarationNode.validateState(TypeDeclarationNode.java:152)
	at org.raml.v2.internal.impl.commons.phase.TypeValidationPhase.apply(TypeValidationPhase.java:40)
	at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
	at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:116)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:100)
	at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:95)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:37)
	at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:18)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.d(ExternalToolPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javaduke** [comment] 2017-03-09 14:16
Can you please attach your RAML file? What are the exact steps to reproduce?

**Comment by mikeder** [comment] 2017-03-31 19:45
I ran into this error when I had a property type integer defined with enum that contained a range:

```
...
body:
  properties:
    error:
      type: integer
      enum: [1,2,3,4-10]
      example: 1
...
```

vs.

```
...
body:
  properties:
    error:
      type: integer
      enum: [1,2,3,4,5,6,7,8,9,10]
      example: 1
...
```

RAML spec doesn't appear to allow a range of integers like this in enum, but this exception crashes the whole plugin.

**Comment by javaduke** [comment] 2017-04-03 14:33
This is actually not a bug - according to our RAML team, ranges of integer are currently not supported by the RAML parser. I'm going to close this for now.

**Closed by javaduke** 2017-04-03 14:33 UTC
