### ISSUE TITLE
Ramlplugin: NullPointerException on referencing non existing traits

### ISSUE THREAD

**Issue by Sevyls** [machaval/mule-intellij-plugins#58] opened 2016-10-24 13:45 UTC
**In Raml Plugin for IntelliJ, Version 0.7 using IntelliJ IDEA 2016.2.5** 

When referencing a not existing trait in an 

```
traits:
 - bla:
      ...
 - blubb:
     ...
...

post: 
  is: [bla, nonexistingtrait] 
```

i.e. defining a reference before the definition was written:

null

```
java.lang.NullPointerException
    at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.applyTrait(ResourceTypesTraitsTransformer.java:200)
    at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.checkTraits(ResourceTypesTraitsTransformer.java:114)
    at org.raml.v2.internal.impl.commons.phase.ResourceTypesTraitsTransformer.transform(ResourceTypesTraitsTransformer.java:88)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:45)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.yagi.framework.phase.TransformationPhase.apply(TransformationPhase.java:54)
    at org.raml.v2.internal.impl.v08.Raml08Builder.build(Raml08Builder.java:51)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:114)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:98)
    at org.raml.v2.internal.impl.RamlBuilder.build(RamlBuilder.java:93)
    at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:37)
    at org.mule.tooling.lang.raml.annotator.RamlAnnotator.doAnnotate(RamlAnnotator.java:18)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:212)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:260)
    at com.intellij.util.ui.update.MergingUpdateQueue$$Lambda$400/725155089.run(Unknown Source)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:274)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:229)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by javaduke** [comment] 2017-03-04 15:42
Appears to be fixed in later versions of the Raml plugin, I'm unable to reproduce it.

**Closed by javaduke** 2017-03-04 15:42 UTC
